=== niccojacinto/MyResume/docs/StreamingAssets/MyResume.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Dialogues">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Dialogue">
          <xs:complexType mixed="true">
            <xs:sequence minOccurs="0">
              <xs:element maxOccurs="unbounded" name="Response">
                <xs:complexType>
                  <xs:attribute name="next_id" type="xs:string" use="required" />
                  <xs:attribute name="text" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
            <xs:attribute name="speaker" type="xs:string" use="required" />
            <xs:attribute name="next_id" type="xs:string" use="required" />
            <xs:attribute name="image_id" type="xs:string" use="required" />
            <xs:attribute name="image_pos" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== niccojacinto/MyResume/docs/StreamingAssets/MyResume.xml
<?xml version="1.0" encoding="utf-8"?>
<Dialogues xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MyResume.xsd">
  <Dialogue id="comein" speaker="You" next_id="" image_id="" image_pos="">Come in!</Dialogue>
  <Dialogue id="introduction1" speaker="You" next_id="introduction2" image_id="" image_pos="">Hello, welcome -- its good to see that you could make it... have a seat.</Dialogue>
  <Dialogue id="introduction2" speaker="???" next_id="introduction3" image_id="portrait2" image_pos="">Thank you, it's good to be here.</Dialogue>
  <Dialogue id="introduction3" speaker="You" next_id="introduction4" image_id="" image_pos="">So let's get this started shall we?</Dialogue>
  <Dialogue id="introduction4" speaker="You" next_id="introduction5" image_id="" image_pos="">May I address you as "Niccolo"?</Dialogue>
  <Dialogue id="introduction5" speaker="Nicco" next_id="introduction6" image_id="portrait2" image_pos="">I usually go by "Nicco" or "Nix", whichever one you'd prefer.</Dialogue>
  <Dialogue id="introduction6" speaker="You" next_id="introduction7" image_id="" image_pos="">Sounds good, that works for me.</Dialogue>
  <Dialogue id="introduction7" speaker="You" next_id="[TUTORIAL]" image_id="" image_pos="">So Nicco, let's talk about some items in your resume...</Dialogue>
  <Dialogue id="tutorial1" speaker="Tutorial" next_id="" image_id="pxArt-qm" image_pos="">&lt;color=yellow&gt;Ask about items on the resume by clicking on it.&lt;/color&gt;</Dialogue>
  <Dialogue id="R-ClickMe" speaker="Tutorial" next_id="tutorial2" image_id="pxArt-qm" image_pos="">&lt;color=yellow&gt;You will get a short description about your selection here.&lt;/color&gt;</Dialogue>
  <Dialogue id="tutorial2" speaker="Tutorial" next_id="tutorial3" image_id="pxArt-qm" image_pos=""> &lt;color=yellow&gt;Sometimes you can get possible responses...&lt;/color&gt;
    <Response next_id="tutorial3" text="&quot;Why does this resume even need a tutorial...&quot;"></Response>
  </Dialogue>
  <Dialogue id="tutorial3" speaker="Tutorial" next_id="[TUTORIALEND]" image_id="pxArt-qm" image_pos=""> &lt;color=yellow&gt;Or &lt;color=#00ffffff&gt;&lt;link=https://www.linkedin.com/in/niccojacinto&gt;[ LINKS ]&lt;/link&gt;&lt;/color&gt; you can click, so don't click on a link if you don't want to open anything.&lt;/color&gt;
    <Response next_id="[TUTORIALEND]" text="[ End Tutorial ]"></Response>
  </Dialogue>
  <Dialogue id="R-nicco" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Yep, that's me. I go by either Nicco or Nix, whichever you prefer.</Dialogue>
  <Dialogue id="R-phone" speaker="Nicco" next_id="" image_id="pxArt-mobileicon" image_pos="">That's my mobile phone number. I'd very much prefer to be emailed though!
    <Response next_id="R-phone2" text="Can I leave you text messages?"></Response>
    <Response next_id="R-phone3" text="How about other forms of contact?"></Response>
  </Dialogue>
  <Dialogue id="R-phone2" speaker="Nicco" next_id="R-phone" image_id="portrait2" image_pos="">Absolutely! Leaving a voicemail is also good if you're unable to reach me!</Dialogue>
  <Dialogue id="R-phone3" speaker="Nicco" next_id="R-phone" image_id="portrait2" image_pos="">Certainly, we can talk about other forms of communication in private.</Dialogue>
  <Dialogue id="R-linkedin" speaker="Nicco" next_id="" image_id="pxArt-LinkedIn" image_pos="">You can view my LinkedIn profile &lt;color=#00ffffff&gt;&lt;link=https://www.linkedin.com/in/niccojacinto&gt;[ here ]&lt;/link&gt;&lt;/color&gt;.</Dialogue>
  <Dialogue id="R-email" speaker="Nicco" next_id="" image_id="" image_pos="">If you have setup your emailing preferences, you can send me a message by clicking &lt;color=#00ffffff&gt;&lt;link=mailto:niccolo.jacinto@gmail.com?subject=Hi%20There!&amp;body=Nice%20resume!&gt;[ here ]&lt;/link&gt;&lt;/color&gt;.</Dialogue>
  <Dialogue id="R-github" speaker="Nicco" next_id="" image_id="pxArt-Github" image_pos="">If you haven't yet, you can view my github profile&lt;color=#00ffffff&gt;&lt;link=https://github.com/niccojacinto&gt; [ here ]&lt;/link&gt;&lt;/color&gt;</Dialogue>
  <Dialogue id="R-loc" speaker="Nicco" next_id="R-loc2" image_id="portrait2" image_pos="">Visit me &lt;color=#00ffffff&gt;&lt;link=https://goo.gl/maps/NV693kDWnFPob98X7&gt;[ here ]&lt;/link&gt;&lt;/color&gt;</Dialogue>
  <Dialogue id="R-loc2" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Okay, that's not really where I live. It's classified.</Dialogue>
  <Dialogue id="R-soq_csharp" speaker="Nicco" next_id="" image_id="" image_pos="">Most of my projects, both professional and hobby ones are done in C#, so I'm most comfortable with that language.</Dialogue>
  <Dialogue id="R-soq_mechanics" speaker="Nicco" next_id="R-soq_mechanics2" image_id="portrait2" image_pos="">I've protoyped a lot of mechanics I wanted to just 'try' out.</Dialogue>
  <Dialogue id="R-soq_mechanics2" speaker="Nicco" next_id="R-soq_mechanics3" image_id="portrait2" image_pos="">Sometimes they're part of a project, but most of the time they're not so I don't really save them.</Dialogue>
  <Dialogue id="R-soq_mechanics3" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Like.. there's this rubixcube-like meets tetris inventory style system I was playing around with for VR. It was quite fun to make. :D</Dialogue>
  <Dialogue id="R-soq_entrylvl" speaker="Nicco" next_id="R-soq_entrylvl2" image_id="portrait2" image_pos="">I think I've reached the point where I want to work on projects on a slightly bigger scale. I believe I can start working on a project and learn from it since I am a blank slate and still have much to learn.
    <Response next_id="R-soq_entrylvl2" text="Are you open to other roles besides programming?"></Response>
  </Dialogue>
  <Dialogue id="R-soq_entrylvl2" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Yep. Like I said, I have much to learn from across different fields so I'm open to other roles as well.</Dialogue>
  <Dialogue id="R-soq_languages" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">C# is my preferred language, but I've also dabbled around other languages depending on the situation. It may take me a while to review and re-learn the language in question though.</Dialogue>
  <Dialogue id="R-soq_problemsolving" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Solving issues just comes with the job. Off by one errors, Heisenbugs (LOL), order of execution errors, design flaws.</Dialogue>
  <Dialogue id="R-soq_collab" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">While flying solo certainly is fun and liberating in its own way. I'm certain working with various and more experienced talents would shift the fun in a different way!</Dialogue>
  <Dialogue id="R-soq_upskilling" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Eventually, I do want more experience working around Networking, exploring AI integration in games, more VR/AR applications, and last but not least.. procedural generation concepts.</Dialogue>
  <Dialogue id="R-ts" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">Pretty straightforward here... you can see tools I've used, but didn't necessarily include a lot of detail. For example.. I mostly use Linux Mint for just powering my slowly dying laptop that I rarely use.</Dialogue>
  <Dialogue id="R-educ_npower" speaker="Nicco" next_id="" image_id="pxArt-npower" image_pos="">Might seem weird having this, but I did take a slight interest in data. Also from what I've learned, there can be game applications from it, and it does involve some degree of programming using Python for example.</Dialogue>
  <Dialogue id="R-educ_googleit" speaker="Nicco" next_id="" image_id="portrait2" image_pos="">This is my I.T. bit. It's very fundamental, but it did give me a small glimpse of the IT world. I was also reading Michel Meyer's CompTIA on the side (although never actually took the certification) and there was a LOT of information there I wouldn't have normally come across.</Dialogue>
  <Dialogue id="R-educ_humber" speaker="Nicco" next_id="" image_id="pxArt-humber" image_pos="">I took game programming courses in Humber. I was quite stressful but also fun! Shoutout to Kris Alexander! (definitely a passionate guy when it comes to games)</Dialogue>
  <Dialogue id="R-exp_acid" speaker="Nicco" next_id="" image_id="pxArt-acid" image_pos="">I worked on several acid projects...
    <Response next_id="R-acidgp" text="Tell me about GoPhysio..."></Response>
    <Response next_id="R-acidcvrep" text="Tell me about Coachella Valley Repertory..."></Response>
    <Response next_id="R-acidpenn" text="Tell me about Penn Highlands..."></Response>
    <Response next_id="R-acidother" text="Anything else?"></Response>
  </Dialogue>
  <Dialogue id="R-acidgp" speaker="Nicco" next_id="R-acidgp2" image_id="portrait2" image_pos="">GoPhysio was basically software installed on a 3D camera that general practitioners would use to monitor a patient's exercise routine...</Dialogue>
  <Dialogue id="R-acidgp2" speaker="Nicco" next_id="R-exp_acid" image_id="portrait2" image_pos="">I worked on product execution flow, importing assets, maintenance, device API, and UI.</Dialogue>
  <Dialogue id="R-acidcvrep" speaker="Nicco" next_id="R-acidcvrep2" image_id="portrait2" image_pos="">CVRep was a remote controlled donor wall project.</Dialogue>
  <Dialogue id="R-acidcvrep2" speaker="Nicco" next_id="R-exp_acid" image_id="portrait2" image_pos="">I worked on the entire screen display and remote software along with the mobile API to front-end.</Dialogue>
  <Dialogue id="R-acidpenn" speaker="Nicco" next_id="R-acidpenn2" image_id="portrait2" image_pos="">Penn was a donor wall project that went on Penn Highlands Healthcare.</Dialogue>
  <Dialogue id="R-acidpenn2" speaker="Nicco" next_id="R-exp_acid" image_id="portrait2" image_pos="">I mostly worked on UI on a seriously short timeframe.</Dialogue>
